# Generated by Django 4.1.2 on 2022-11-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_rename_time_event_start_time_event_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="imp",
            field=models.CharField(default="notimp", max_length=30),
        ),
    ]
